version: '2'

services:
  web:
    image: nginx
    container_name: web
    ports:
      - "4200:80"
    volumes:
      - ./web/dist/web:/var/www/html/website
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  app:
    image: node:carbon
    container_name: app
    user: "node"
    working_dir: /home/node/app
    ports:
      - "8080:8080"
    volumes:
      - ./app:/home/node/app
    command: "npm start"